# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "convert_to_poetry", "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-airodor-wifi-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3
    - name: Install poetry
      working-directory: ${{github.workspace}}/airodor_wifi_api/
      run: |
        poetry install
    - name: Test with pytest
      working-directory: ${{github.workspace}}/airodor_wifi_api/
      run: |
        poetry run pytest
